<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'RebaseData\\' => array($vendorDir . '/rebasedata/php-client/src'),
    'Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-message/src'),
    'GuzzleHttp\\Psr7\\' => array($vendorDir . '/guzzlehttp/psr7/src'),
    'GuzzleHttp\\Promise\\' => array($vendorDir . '/guzzlehttp/promises/src'),
    'GuzzleHttp\\' => array($vendorDir . '/guzzlehttp/guzzle/src'),
    'BenTools\\StringCombinations\\' => array($vendorDir . '/bentools/string-combinations/src'),
    'BenTools\\CartesianProduct\\' => array($vendorDir . '/bentools/cartesian-product/src'),
);
