<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitb88ebc06584be678a32d25bdca60db2e
{
    public static $files = array (
        '7b11c4dc42b3b3023073cb14e519683c' => __DIR__ . '/..' . '/ralouphie/getallheaders/src/getallheaders.php',
        'c964ee0ededf28c96ebd9db5099ef910' => __DIR__ . '/..' . '/guzzlehttp/promises/src/functions_include.php',
        'a0edc8309cc5e1d60e3047b5df6b7052' => __DIR__ . '/..' . '/guzzlehttp/psr7/src/functions_include.php',
        'b01d94a15e6cb786a6fda957d332a971' => __DIR__ . '/..' . '/bentools/cartesian-product/src/function.php',
        '37a3dc5111fe8f707ab4c132ef1dbc62' => __DIR__ . '/..' . '/guzzlehttp/guzzle/src/functions_include.php',
        '3d5a17dba9ac7092b6c8abc62c32b6af' => __DIR__ . '/..' . '/bentools/string-combinations/src/functions.php',
    );

    public static $prefixLengthsPsr4 = array (
        'R' => 
        array (
            'RebaseData\\' => 11,
        ),
        'P' => 
        array (
            'Psr\\Http\\Message\\' => 17,
        ),
        'G' => 
        array (
            'GuzzleHttp\\Psr7\\' => 16,
            'GuzzleHttp\\Promise\\' => 19,
            'GuzzleHttp\\' => 11,
        ),
        'B' => 
        array (
            'BenTools\\StringCombinations\\' => 28,
            'BenTools\\CartesianProduct\\' => 26,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'RebaseData\\' => 
        array (
            0 => __DIR__ . '/..' . '/rebasedata/php-client/src',
        ),
        'Psr\\Http\\Message\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/http-message/src',
        ),
        'GuzzleHttp\\Psr7\\' => 
        array (
            0 => __DIR__ . '/..' . '/guzzlehttp/psr7/src',
        ),
        'GuzzleHttp\\Promise\\' => 
        array (
            0 => __DIR__ . '/..' . '/guzzlehttp/promises/src',
        ),
        'GuzzleHttp\\' => 
        array (
            0 => __DIR__ . '/..' . '/guzzlehttp/guzzle/src',
        ),
        'BenTools\\StringCombinations\\' => 
        array (
            0 => __DIR__ . '/..' . '/bentools/string-combinations/src',
        ),
        'BenTools\\CartesianProduct\\' => 
        array (
            0 => __DIR__ . '/..' . '/bentools/cartesian-product/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitb88ebc06584be678a32d25bdca60db2e::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitb88ebc06584be678a32d25bdca60db2e::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
